experiment_name: sample_least_squares_gan

gpus: 1
cpus: 3

dataset: "MNIST"
mnist_shape: !!python/tuple [1, 32, 32]

img_height: 32
img_width: 32
channels: 1

batch_size: 64
lr: 0.0002
b1: 0.5
b2: 0.999
latent_dim: 100